function(add_all_subdirectories)
    set(base_dir ${CMAKE_CURRENT_SOURCE_DIR})
    file(GLOB children RELATIVE "${base_dir}" "${base_dir}/*")
    foreach(child ${children})
        if(IS_DIRECTORY "${base_dir}/${child}" AND
           EXISTS "${base_dir}/${child}/CMakeLists.txt")
            add_subdirectory("${base_dir}/${child}")
        endif()
    endforeach()
endfunction()
